spacewalk-startup-helper check status of reportdb creation (#5117)

diff --git a/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb b/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
--- a/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
+++ b/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
@@ -123,7 +123,7 @@ create() {
         FQDN="localhost"
     else
         [ ! -s "$SSL_CERT" ] && {
-            echo "SSL Certificate ($SSL_CERT) required to setup the reporting database" >&2
+            echo "SSL Certificate ($SSL_CERT) is required to setup the reporting database" >&2
             exit 1
         }
         [ ! -s "$CA_CERT" ] && {
