SSL certificates are required to setup the report db

diff --git a/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb b/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
--- a/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
+++ b/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
@@ -108,14 +108,20 @@ if [ -x /usr/bin/lsof ]; then
     LSOF="/usr/bin/lsof"
 fi
 RUNUSER=runuser
-#if isSUSE ; then
-#    RUNUSER=/usr/bin/su
-#fi
 FQDN=$(hostname -f)
 SSL_CERT=/etc/pki/tls/certs/spacewalk.crt
 SSL_KEY=/etc/pki/tls/private/pg-spacewalk.key
 
 create() {
+    [ ! -s "$SSL_CERT" ] && {
+        echo "SSL Certificate ($SSL_CERT) required to setup the reporting database" >&2
+        exit 1
+    }
+    [ ! -s "$SSL_KEY" ] && {
+        echo "SSL Private Key ($SSL_KEY) not found" >&2
+        exit 1
+    }
+
     [ -z "$PGNAME" ] && ask true "Database name: " PGNAME
     [ -z "$PGUSER" ] && ask true "Database user: " PGUSER
     [ -z "$PGPASSWORD" ] && ask false "Database password: " PGPASSWORD
@@ -165,29 +171,18 @@ work_mem = 2560kB
 EOF
     fi
 
-    if [ -e $SSL_CERT -a -e $SSL_KEY ]; then
-        postgres_reconfig "ssl" "on"
-	postgres_reconfig "ssl_cert_file" "'$SSL_CERT'"
-	postgres_reconfig "ssl_key_file" "'$SSL_KEY'"
-    fi
+    # SSL setup is required when opening DB to the world
+    postgres_reconfig "ssl" "on"
+    postgres_reconfig "ssl_cert_file" "'$SSL_CERT'"
+    postgres_reconfig "ssl_key_file" "'$SSL_KEY'"
 
     echo "$ADDRESS"|grep -q '127.0.0.1\|*' || ADDRESS="$ADDRESS, 127.0.0.1"
     postgres_reconfig "listen_addresses" "'$ADDRESS'"
 
     sysctl kernel.shmmax | ( read v v v ; LIMIT=5000000000 ; if (("$v"0 < $LIMIT )) ; then sysctl "kernel.shmmax=$LIMIT" >> /etc/sysctl.conf ; fi )
 
-#    cat >> $PG_IDENT <<EOF
-#
-#usermap root postgres
-#usermap postgres postgres
-#
-#EOF
     if $STANDALONE; then
         sed -i 's/^\([^#].*\)$/### next line has been commented out by uyuni-setup-reportdb: ###\n##\1/ ' $PG_HBA
-    else
-        # disable entries allowing access to all
-	sed -i 's/^host[[:space:]]\+all[[:space:]]\+all[[:space:]]\+0.0.0.0\/0[[:space:]]\+md5//' $PG_HBA
-        sed -i 's/^host[[:space:]]\+all[[:space:]]\+all[[:space:]]\+::\/0[[:space:]]\+md5//' $PG_HBA
     fi
     cat >> $PG_HBA <<EOF
 local $PGNAME $PGUSER scram-sha-256
