verify is user is present in non-interactive

diff --git a/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb-user b/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb-user
--- a/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb-user
+++ b/spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb-user
@@ -185,6 +185,11 @@ else ### INTERACTIVE=0
     exit 1
   fi
   
+  if [ -z $USER ]; then
+    echo "User is missing. Exit"
+    exit 1
+  fi
+  
   if [ -z $DBPASSWORD ]; then
     echo "Password is missing. Exit"
     exit 1
