Added sudo support

diff --git a/spacewalk/certs-tools/spacewalk-ssh-push-init b/spacewalk/certs-tools/spacewalk-ssh-push-init
--- a/spacewalk/certs-tools/spacewalk-ssh-push-init
+++ b/spacewalk/certs-tools/spacewalk-ssh-push-init
@@ -110,6 +110,16 @@ if [ "${USE_TUNNEL}" = "Y" ]; then
     exit 1
   fi
 
+  # Set the sudo command, it'll be blank if no sudo user was set
+  # Set the user variable, defaults to root if no sudo user is set
+  if [ -z "${SUDO_USER}" ]; then
+    SUDO_CMD=
+    USER=root
+  else
+    SUDO_CMD=sudo
+    USER=${SUDO_USER}
+  fi
+
   # Generating the enablement script
   ENABLE=`mktemp`
   echo "* Generating tunnel setup script (${ENABLE})"
@@ -193,44 +203,44 @@ fi
 
 # Copy public key to the client, require 'ssh-rsa' as host key algorithm
 echo "* Pushing SSH key to '${CLIENT}', please login as root:"
-ssh-copy-id -o HostKeyAlgorithms=ssh-rsa -i ${SSH_IDENTITY}.pub root@${CLIENT} 2>&1
+ssh-copy-id -o HostKeyAlgorithms=ssh-rsa -i ${SSH_IDENTITY}.pub ${USER}@${CLIENT} 2>&1
 exit_in_case_of_error
 
 # Remove duplicate entries from authorized keys
 echo "* Removing duplicate host keys remotely"
 AUTH_KEYS=~/.ssh/authorized_keys
 AUTH_KEYS2=~/.ssh/authorized_keys2
-ssh -i ${SSH_IDENTITY} root@${CLIENT} "[ -f ${AUTH_KEYS} ] && sed -i \"\\\$!{/${SSH_KEY_COMMENT}/d;}\" ${AUTH_KEYS} && echo 'Cleaned: ${AUTH_KEYS}' || echo 'Skipping: ${AUTH_KEYS} (not found)'"
-ssh -i ${SSH_IDENTITY} root@${CLIENT} "[ -f ${AUTH_KEYS2} ] && sed -i \"\\\$!{/${SSH_KEY_COMMENT}/d;}\" ${AUTH_KEYS2} && echo 'Cleaned: ${AUTH_KEYS2}' || echo 'Skipping: ${AUTH_KEYS2} (not found)'"
+ssh -i ${SSH_IDENTITY} ${USER}@${CLIENT} "[ -f ${AUTH_KEYS} ] && sed -i \"\\\$!{/${SSH_KEY_COMMENT}/d;}\" ${AUTH_KEYS} && echo 'Cleaned: ${AUTH_KEYS}' || echo 'Skipping: ${AUTH_KEYS} (not found)'"
+ssh -i ${SSH_IDENTITY} ${USER}@${CLIENT} "[ -f ${AUTH_KEYS2} ] && sed -i \"\\\$!{/${SSH_KEY_COMMENT}/d;}\" ${AUTH_KEYS2} && echo 'Cleaned: ${AUTH_KEYS2}' || echo 'Skipping: ${AUTH_KEYS2} (not found)'"
 exit_in_case_of_error
 
 # Copy scripts to the client
 if [ -n "${BOOTSTRAP}" ]; then
   echo "* Pushing scripts to the client"
   if [ "${USE_TUNNEL}" = "Y" ]; then
-    scp -i ${SSH_IDENTITY} ${ENABLE} root@${CLIENT}:enable.sh
+    scp -i ${SSH_IDENTITY} ${ENABLE} ${USER}@${CLIENT}:enable.sh
     exit_in_case_of_error
   fi
-  scp -i ${SSH_IDENTITY} ${BOOTSTRAP} root@${CLIENT}:bootstrap.sh
+  scp -i ${SSH_IDENTITY} ${BOOTSTRAP} ${USER}@${CLIENT}:bootstrap.sh
   exit_in_case_of_error
 fi
 
 # Enablement, registration and cleanup
 if [ "${USE_TUNNEL}" = "Y" ]; then
   echo "* Enabling client for SSH Push via tunnel"
-  ssh -i ${SSH_IDENTITY} root@${CLIENT} "bash enable.sh"
+  ssh -i ${SSH_IDENTITY} ${USER}@${CLIENT} "${SUDO_CMD} bash enable.sh"
   exit_in_case_of_error
 
   echo "* Registering client with SUSE Manager: ${CLIENT}"
-  ssh -i ${SSH_IDENTITY} -R ${PORT_HTTP}:${HOSTNAME}:80 -R ${PORT_HTTPS}:${HOSTNAME}:443 root@${CLIENT} 'bash bootstrap.sh'
+  ssh -i ${SSH_IDENTITY} -R ${PORT_HTTP}:${HOSTNAME}:80 -R ${PORT_HTTPS}:${HOSTNAME}:443 ${USER}@${CLIENT} '${SUDO_CMD} bash bootstrap.sh'
   exit_in_case_of_error
 
   echo "* Cleaning up temporary files"
-  ssh -i ${SSH_IDENTITY} root@${CLIENT} "rm -f enable.sh bootstrap.sh client-config-overrides-tunnel.txt client_config_update.py"
+  ssh -i ${SSH_IDENTITY} ${USER}@${CLIENT} "rm -f enable.sh bootstrap.sh client-config-overrides-tunnel.txt client_config_update.py"
   rm -fv ${ENABLE} ${BOOTSTRAP}
 elif [ -n "${BOOTSTRAP}" ]; then
   # Simple registration with given bootstrap script
   echo "* Registering client with SUSE Manager: ${CLIENT}"
-  ssh -i ${SSH_IDENTITY} root@${CLIENT} 'bash bootstrap.sh'
+  ssh -i ${SSH_IDENTITY} ${USER}@${CLIENT} '${SUDO_CMD} bash bootstrap.sh'
   exit_in_case_of_error
 fi
