Package 'snapper' is now optional

diff --git a/susemanager/bin/mgr-setup b/susemanager/bin/mgr-setup
--- a/susemanager/bin/mgr-setup
+++ b/susemanager/bin/mgr-setup
@@ -254,12 +254,25 @@ host $MANAGER_DB_NAME $MANAGER_USER ::1/128 md5
     systemctl restart postgresql
 }
 
+check_mksubvolume() {
+    if ! command -v mksubvolume &> /dev/null
+    then
+        echo "'mksubvolume' not found. Installing package 'snapper'"
+        $(command -v zypper || command -v dnf) --quiet install -y snapper
+        if ! [ $? -eq 0 ]; then
+            echo "Please install the package 'snapper' manually."
+            exit 1
+        fi
+    fi
+}
+
 check_btrfs_dirs() {
 DIR="/var/spacewalk"
 if [ ! -d $DIR ]; then
     FSTYPE=`df -T \`dirname $DIR\` | tail -1 | awk '{print $2}'`
     echo -n "Filesystem type for $DIR is $FSTYPE - "
     if [ $FSTYPE == "btrfs" ]; then
+        check_mksubvolume
         echo "creating nCoW subvolume."
         mksubvolume --nocow $DIR
     else
@@ -279,6 +292,7 @@ if [ $FSTYPE == "btrfs" ]; then
     TESTDIR=`basename $DIR`
     btrfs subvolume list /var | grep "$TESTDIR" > /dev/null
     if [ ! $? -eq 0 ]; then
+        check_mksubvolume
         echo "creating subvolume."
         mv $DIR ${DIR}.sav
         mksubvolume $DIR
